version: "3"
services:

  db:
    build: .
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Sample
    ports:
      - 8081:5432
    hostname: db

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@sample.com
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin